//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFarmacia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_precios
    {
        public int ID_TEMP { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal PRECIO { get; set; }
    
        public virtual Temp2 Temp2 { get; set; }
    }
}
