//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFarmacia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int ID_PRODUCTO { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public int CANTIDAD_PRODUCTO { get; set; }
        public int ID_UNIDAD { get; set; }
        public byte ID_PRESENTACION { get; set; }
    }
}
