//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFarmacia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temp2()
        {
            this.Bitacora_precios = new HashSet<Bitacora_precios>();
        }
    
        public int ID_TEMP { get; set; }
        public string NOMBRE { get; set; }
        public byte ID_PRESENTACION { get; set; }
        public decimal PRECIO { get; set; }
        public string COMPONENTES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bitacora_precios> Bitacora_precios { get; set; }
        public virtual Presentaciones Presentaciones { get; set; }
    }
}
