//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaFarmacia.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VVentas
    {
        public System.DateTime FECHA { get; set; }
        public string NOMBRE { get; set; }
        public byte CANTIDAD { get; set; }
        public string MEDICAMENTO { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_PRODUCTO { get; set; }
    }
}
